// Centralized native GameplayTag declarations for the TPS demo (Module 1: GAS Core).

#pragma once

#include "NativeGameplayTags.h"

namespace TSGameplayTags
{
	// State.Movement.*
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Sprinting);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Sliding);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Crouching);

	// State.Combat.*
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_ADS);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Firing);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Reloading);

	// State.Weapon.*
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_Switching);

	// State.Dead
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	// Ability.* (input mapping)
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reload);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Slide);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WeaponSwitch);

	// Event.Combat.*
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Hit);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Kill);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_TakeDamage);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Death);

	// Weapon.Slot.*
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Slot_Primary);
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Slot_Secondary);

	// Cooldown.*
	AI_TPSDEMO2_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Slide);
}
